const PRODUCTS = [
  {
    id: "aparador-uspallata",
    name: "Aparador Uspallata",
    category: "Guardado",
    price: 1480000,
    image: "Kit de imágenes/Aparador Uspallata.png",
    short: "Nogal argentino, esterilla natural y una silueta que recupera el optimismo de los años sesenta.",
    description: "El Uspallata combina una caja de nogal de veta continua con frente de esterilla tejida a mano y tapa mineral clara. Sus puertas corredizas guardan vajilla, libros o textiles sin interrumpir la pureza de la línea.",
    materials: "Nogal argentino certificado, esterilla natural, herrajes de latón y terminación con aceite de lino.",
    dimensions: "180 × 45 × 78 cm",
    making: "Ensamblado y tejido a mano en nuestro taller de San Cristóbal. Tiempo estimado: 6 a 8 semanas.",
    featured: true,
    badge: "Pieza insignia"
  },
  {
    id: "biblioteca-recoleta",
    name: "Biblioteca Recoleta",
    category: "Guardado",
    price: 1890000,
    image: "Kit de imágenes/Biblioteca Recoleta.png",
    short: "Una estructura abierta y liviana que ordena sin quitarle aire al ambiente.",
    description: "La Recoleta está pensada como una arquitectura doméstica: estantes amplios, modulación serena y encuentros de latón que celebran el oficio. Puede funcionar como biblioteca o divisor de ambientes.",
    materials: "Petiribí certificado, uniones de latón y acabado de cera de abejas de origen local.",
    dimensions: "220 × 38 × 190 cm",
    making: "Construcción modular de encastres precisos, terminada a mano. Tiempo estimado: 8 semanas.",
    featured: false,
    badge: "Edición de taller"
  },
  {
    id: "butaca-mendoza",
    name: "Butaca Mendoza",
    category: "Asientos",
    price: 895000,
    image: "Kit de imágenes/Butaca Mendoza.png",
    short: "Terciopelo rosa polvoriento y apoyabrazos de madera para una pausa verdaderamente cómoda.",
    description: "Con proporciones generosas y una inclinación amable, la Mendoza invita a bajar el ritmo. El tapizado rosa polvoriento aporta carácter sin perder calidez, mientras la estructura deja visible la nobleza de la madera.",
    materials: "Guatambú certificado, espuma de alta resiliencia y terciopelo de fibras recuperadas.",
    dimensions: "76 × 82 × 84 cm",
    making: "Estructura encastrada, cinchado manual y tapizado por artesanos locales. Tiempo estimado: 5 semanas.",
    featured: true,
    badge: "Favorita"
  },
  {
    id: "escritorio-costa",
    name: "Escritorio Costa",
    category: "Trabajo",
    price: 1320000,
    image: "Kit de imágenes/Escritorio Costa.png",
    short: "Superficie de cuero vegetal, cajones suspendidos y orden para las ideas de todos los días.",
    description: "Costa reinterpreta el escritorio ejecutivo de mediados de siglo con una escala contemporánea. La bandeja superior organiza objetos pequeños y los cajones suspendidos mantienen libre el espacio de trabajo.",
    materials: "Nogal certificado, cuero curtido vegetal, tiradores de latón y adhesivos de bajo COV.",
    dimensions: "150 × 70 × 76 cm",
    making: "Carpintería de precisión y superficie cosida a mano. Tiempo estimado: 7 semanas.",
    featured: true,
    badge: "Nuevo"
  },
  {
    id: "mesa-comedor-pampa",
    name: "Mesa Comedor Pampa",
    category: "Mesas",
    price: 2140000,
    image: "Kit de imágenes/Mesa Comedor Pampa.png",
    short: "Una mesa sólida y honesta, preparada para sobremesas largas y muchas historias.",
    description: "La Pampa nace de una tapa de gran espesor y bases escultóricas con vacío central. Su presencia es rotunda, pero las aristas suavizadas y la veta continua mantienen una expresión cercana.",
    materials: "Petiribí macizo certificado, aceite de lino natural y protectores de fieltro reciclado.",
    dimensions: "220 × 100 × 75 cm",
    making: "Cada tapa se selecciona y calibra de forma individual. Tiempo estimado: 8 a 10 semanas.",
    featured: false,
    badge: "Madera maciza"
  },
  {
    id: "mesa-centro-araucaria",
    name: "Mesa de Centro Araucaria",
    category: "Mesas",
    price: 780000,
    image: "Kit de imágenes/Mesa de Centro Araucaria.png",
    short: "Vidrio de bordes suaves sobre una base orgánica inspirada en el paisaje argentino.",
    description: "Araucaria equilibra transparencia y materia. El vidrio revela una base de tres apoyos curvos, tallados para encontrarse en un gesto continuo que cambia según el punto de vista.",
    materials: "Base de nogal recuperado, vidrio templado de 12 mm y acabado con cera natural.",
    dimensions: "120 × 80 × 38 cm",
    making: "Base tallada y pulida a mano; vidrio producido a medida. Tiempo estimado: 5 semanas.",
    featured: true,
    badge: "Material recuperado"
  },
  {
    id: "mesa-noche-aconcagua",
    name: "Mesa de Noche Aconcagua",
    category: "Guardado",
    price: 525000,
    image: "Kit de imágenes/Mesa de Noche Aconcagua.png",
    short: "Guardado silencioso y madera cálida para acompañar el final del día.",
    description: "Aconcagua concentra utilidad en un volumen sereno. El estante abierto mantiene a mano las lecturas y el cajón profundo esconde aquello que preferís fuera de vista.",
    materials: "Nogal certificado, tirador de latón envejecido y acabado al aceite natural.",
    dimensions: "62 × 42 × 45 cm",
    making: "Frentes seleccionados por continuidad de veta y cajón con encastre cola de milano. Tiempo estimado: 4 semanas.",
    featured: false,
    badge: "Hecha a mano"
  },
  {
    id: "silla-trabajo-belgrano",
    name: "Silla de Trabajo Belgrano",
    category: "Trabajo",
    price: 745000,
    image: "Kit de imágenes/Silla de Trabajo Belgrano.png",
    short: "Ergonomía contemporánea envuelta en madera y verde salvia.",
    description: "Belgrano lleva la sensibilidad del mobiliario doméstico al espacio de trabajo. Su respaldo respirable, apoyo lumbar y mecanismos regulables acompañan la postura sin adoptar una estética corporativa.",
    materials: "Estructura laminada de nogal, tejido reciclado, aluminio recuperado y ruedas de bajo impacto.",
    dimensions: "68 × 68 × 96–108 cm",
    making: "Componentes reparables y reemplazables para extender su vida útil. Tiempo estimado: 4 semanas.",
    featured: false,
    badge: "Ergonómica"
  },
  {
    id: "sillas-cordoba",
    name: "Sillas Córdoba",
    category: "Asientos",
    price: 980000,
    image: "Kit de imágenes/Sillas Córdoba.png",
    short: "Un par de sillas livianas, con respaldo de varillas y asiento verde salvia.",
    description: "Las Córdoba reinterpretan la silla peineta con una curva más envolvente. Su estructura liviana resiste el uso cotidiano y el tapizado aporta una nota suave de color.",
    materials: "Guatambú certificado, textil con contenido reciclado y tintes vegetales al agua.",
    dimensions: "48 × 52 × 82 cm cada una",
    making: "Varillas torneadas y respaldo ensamblado a mano. El precio corresponde al par. Tiempo estimado: 5 semanas.",
    featured: false,
    badge: "Par"
  },
  {
    id: "sillon-copacabana",
    name: "Sillón Copacabana",
    category: "Asientos",
    price: 1120000,
    image: "Kit de imágenes/Sillón Copacabana.png",
    short: "Cuero color caramelo y madera oscura en una pieza que mejora con los años.",
    description: "Copacabana tiene la comodidad franca de un sillón de lectura y la elegancia de una pieza heredada. El cuero desarrolla una pátina única, registrando con belleza el paso del tiempo.",
    materials: "Estructura de nogal, cuero de curtido vegetal y relleno de fibras naturales.",
    dimensions: "79 × 84 × 86 cm",
    making: "Bastidor ensamblado, cinchado y tapizado íntegramente a mano. Tiempo estimado: 7 semanas.",
    featured: false,
    badge: "Cuero vegetal"
  },
  {
    id: "sofa-patagonia",
    name: "Sofá Patagonia",
    category: "Asientos",
    price: 2490000,
    image: "Kit de imágenes/Sofá Patagonia.png",
    short: "Tres cuerpos, textura verde salvia y una comodidad pensada para durar generaciones.",
    description: "Patagonia reúne escala familiar, apoyo profundo y líneas limpias. Sus almohadones reversibles y fundas desmontables simplifican el cuidado, mientras la base de madera mantiene el conjunto visualmente liviano.",
    materials: "Madera certificada, cinchas de yute, espuma de larga duración y bouclé reciclado.",
    dimensions: "228 × 92 × 82 cm",
    making: "Estructura garantizada por 10 años y tapizado reparable. Tiempo estimado: 8 semanas.",
    featured: false,
    badge: "Herencia Viva"
  }
];

window.HJ_PRODUCTS = PRODUCTS;
